const ACTION_TYPE = {
    ORDER: {
        ADD_ORDER: 'ADD_ORDER',
        TOGGLE_ORDER: 'TOGGLE_ORDER'
    },
    ORDERS: {
        REMOVE_ORDER: 'REMOVE_ORDER',
        REMOVE_ALL_ORDER: 'REMOVE_ALL_ORDER',
        TOGGLE_ALL_ORDER: 'TOGGLE_ALL_ORDER',
        EDIT: 'EDIT'
    },
    VISIBILITY_FILTER: {
        SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    },
    LANG: {
        SET_LANGUAGE: 'SET_LANGUAGE'
    },
    FETCH: {
        ORDERS_RECEIVED: 'ORDERS_RECEIVED',
        ORDERS_REQUEST_FAILED: 'ORDERS_REQUEST_FAILED'
    }
};

export default ACTION_TYPE;